import { BeforeAfterComparator } from "@/components/marketing/before-after-comparator";
import { FAQ } from "@/components/marketing/faq";
import { SelfServeForm } from "@/components/marketing/self-serve-form";
import { Card, CardContent } from "@/components/ui/card";
import { getSampleBeforeAfters } from "@/lib/samples";

export const dynamic = "force-dynamic";
export const metadata = { title: "MenuLift — AI menu photo enhancement for restaurants" };

const STATS = [
  { figure: "+30%", label: "more orders per item shot", detail: "Menu items with a photo convert at up to 30% higher than text-only items on delivery marketplaces.", source: "DoorDash Merchant Suite, 2024" },
  { figure: "70%", label: "of customers check first", detail: "Seven in ten diners check Google or a delivery app before deciding where to order from or visit.", source: "Google / Ipsos restaurant study" },
  { figure: "<24h", label: "from menu to upload-ready", detail: "Send your menu by 5pm. Photos for every item — newly generated and enhanced — back the next morning.", source: "MenuLift SLA" },
  { figure: "$40–$90/mo", label: "flat pricing per location", detail: "Subscription pricing. Unlimited revisions. All three channels (Google, DoorDash, Uber Eats) included.", source: "Pricing" },
];

export default async function AudienceAPage() {
  const samples = await getSampleBeforeAfters("audience-a");
  return (
    <>
      <section className="border-b bg-gradient-to-b from-background to-muted/30 py-20">
        <div className="container max-w-4xl text-center">
          <div className="mb-4 inline-block rounded-full bg-amber-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-amber-700">
            For restaurants · A photo for every dish on your menu
          </div>
          <h1 className="text-4xl font-bold tracking-tight sm:text-6xl">
            More orders. Every item shot.
          </h1>
          <p className="mt-6 text-lg text-muted-foreground sm:text-xl">
            Listings with a photo on every menu item get up to <span className="font-semibold text-foreground">30% more orders</span>.
            We create photos for the dishes you don't have shot yet, and polish the ones you do —
            delivered upload-ready for Google, DoorDash, and Uber Eats in under 24 hours. From $40/mo.
          </p>
          <div className="mt-8">
            <SelfServeForm fixedServiceId="menu-shoot-full" />
            <p className="mt-3 text-xs text-muted-foreground">
              Free sample on your first photo · no card required · cancel anytime
            </p>
          </div>
        </div>
      </section>

      <section id="why" className="container py-16">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">Why menu photos matter.</h2>
          <p className="mt-3 text-muted-foreground">Photos are the single biggest conversion lever on Google and the delivery apps.</p>
        </div>
        <div className="mx-auto mt-10 grid max-w-5xl gap-4 md:grid-cols-2 lg:grid-cols-4">
          {STATS.map((s) => (
            <Card key={s.figure} className="overflow-hidden">
              <CardContent className="space-y-2 p-6">
                <div className="text-4xl font-bold tracking-tight text-primary">{s.figure}</div>
                <div className="text-sm font-semibold">{s.label}</div>
                <p className="text-sm text-muted-foreground">{s.detail}</p>
                <div className="pt-1 text-[11px] uppercase tracking-wider text-muted-foreground">Source: {s.source}</div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      <section id="samples" className="container py-16">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">Drag the slider.</h2>
          <p className="mt-3 text-muted-foreground">
            Every "after" was generated by the exact pipeline that runs on your submission.
          </p>
        </div>
        <div className="mt-10 grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {samples.map((s) => (
            <div key={s.id} className="space-y-2">
              <BeforeAfterComparator beforeUrl={s.before} afterUrl={s.after} />
              <p className="text-sm text-muted-foreground">{s.caption}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="pricing" className="border-t bg-muted/30 py-16">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold tracking-tight">Pricing.</h2>
            <p className="mt-3 text-muted-foreground">Monthly subscription. Unlimited revisions on every batch.</p>
          </div>
          <div className="mx-auto mt-10 grid max-w-4xl gap-6 md:grid-cols-3">
            <Card><CardContent className="space-y-2 p-6">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Sprint</div>
              <div className="text-3xl font-bold">$40<span className="text-base font-normal text-muted-foreground">/mo</span></div>
              <p className="text-sm text-muted-foreground">Up to 15 items per month — new photos generated for missing items, existing photos enhanced. Google + DoorDash + Uber Eats exports.</p>
            </CardContent></Card>
            <Card className="border-primary"><CardContent className="space-y-2 p-6">
              <div className="text-xs font-semibold uppercase tracking-wider text-primary">+ Full Menu</div>
              <div className="text-3xl font-bold">$69<span className="text-base font-normal text-muted-foreground">/mo</span></div>
              <p className="text-sm text-muted-foreground">Every item on your menu shot — generated for the ones you don't have, enhanced for the ones you do. Storefront hero refresh included. Monthly refresh.</p>
            </CardContent></Card>
            <Card><CardContent className="space-y-2 p-6">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Multi-location</div>
              <div className="text-3xl font-bold">$90<span className="text-base font-normal text-muted-foreground">/mo</span></div>
              <p className="text-sm text-muted-foreground">Per location. Priority generation queue, dedicated brand profile, quarterly menu audit, white-glove onboarding.</p>
            </CardContent></Card>
          </div>
        </div>
      </section>

      <section id="faq" className="container py-16">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">Common questions.</h2>
        </div>
        <div className="mx-auto mt-10 max-w-4xl">
          <FAQ audience="audience-a" />
        </div>
      </section>
    </>
  );
}
